GET http://localhost:3004/todos/

###
GET http://localhost:3004/todos/2/

###

POST http://localhost:3004/todos/
Content-Type: application/json

{
"id": 1,
"todo": "Learn HTML",
"isChecked": false
}

###
PUT http://localhost:3004/todos/
Content-Type: application/json

{
"isChecked": true
}

###
DELETE http://localhost:3004/todos/1/